configuration:
  swagger:
    app: 'File Upload System'
    description: 'API for File Upload System'
    developer: 'Hamza Bakaran'
    email: 'hamza.bakaran@stu.ibu.edu.ba'

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/file-upload
    username: root
    password: r0otH@mza
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop # or any other value based on your requirement

security:
  jwt:
    secret: '2Rgs9gbpx3eQsiY5YOyQgFnHwThLQf7gp3iMAFDHBH9kHg7nn1Mb5FCf6tXaaR3g'

minio:
  endpoint: http://127.0.0.1:9001
  accessKey: wJnHDB9aJenUdNhP9X6P
  secretKey: tFGk0p6939acjxL6t1CPQVSMlvBIQDca0KdSTWCM
  bucketName: file-upload

aws:
  access-key: $access-key
  secret-key: $secret-key
  region:  eu-central-1  # Specify your AWS region here
  s3:
    bucket-name: sdp-file-upload-spring # Specify your S3 bucket name here